### PR TITLE
Deprecate the `tinypilot_repo` variables.

### PR DESCRIPTION
**Pull request by jdeanwallace**
Part of https://github.com/tiny-pilot/ansible-role-tinypilot/issues/218
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/ansible-role-tinypilot/221">Review on CodeApprove</a>

### CODE REVIEW

**Comment by jdeanwallace** [comment]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ansible-role-tinypilot/221)

⏳ @mtlynch please review this Pull Request

**Review by mtlynch — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ansible-role-tinypilot/221)


Approved on CodeApprove
✔️ Approved (1 unresolved comments)

LGTM

<hr />

In: **README.md**:

```
> Line 13
tinypilot_group: tinypilot
```
I think we should just leave the documentation as-is until we create a usable path for Debian packages. Because right now, it's not really practical for users to use the Ansible role with Debian packages because they have to go through a contrived dance of downloading the bundle, extracting the Debian package, and copying it to the target system first.


[](https://goomics.net/50/)



<hr />

👀 @jdeanwallace it's your turn please take a look

**Review by jdeanwallace — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ansible-role-tinypilot/221)



<hr />

In: **README.md**:

```
> Line 13
tinypilot_group: tinypilot
```
Haha makes sense, thanks!

**Review by mtlynch — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ansible-role-tinypilot/221)

Approved: I have approved this change on CodeApprove and all of my comments have been resolved.

**Pull request merged**
