### PR TITLE
Refactor: share common logic between privileged scripts (backport)

### LINKED ISSUE #147: Refactoring: share common logic between privileged scripts
We have some duplication in the [privileged scripts](https://github.com/tiny-pilot/ansible-role-tinypilot/tree/master/files), especially in [pro](https://github.com/tiny-pilot/ansible-role-tinypilot-pro/tree/master/files). For example, the path to the USB gadget / configfs is spelled out in multiple files, or the procedure for (re-)initializing the gadget. It would be clearer, if there was just one source of truth for those values, and defining functions for common procedures could make the scripts more expressive.

An idea would be to pull out a script file with common constants and procedures (e.g. `lib.sh`) that can be `source`’d in the other scripts. Example:

```bash
#!/bin/bash

readonly USB_GADGET_PATH="/sys/kernel/config/usb_gadget/g1"

initialize_gadget() {
  ls /sys/class/udc > "${USB_GADGET_PATH}/UDC"
  chmod 777 /dev/hidg0
  chmod 777 /dev/hidg1
}
```

Then, in [`eject-mass-storage`](https://github.com/tiny-pilot/ansible-role-tinypilot-pro/blob/9525e9a01e46388aa9d41e7beab627a5a4f6fbaf/files/eject-mass-storage#L41):

```bash
source lib.sh # or whatever the file name is

# ...

if "${is_force_mode}"; then
  echo '' > "${USB_GADGET_PATH}/UDC"
  trap initialize_gadget EXIT
fi
```

### PR DESCRIPTION
**Pull request by rw4nn**
Backport the scripts refactor from pro.

Resolves #147.

---
This change is [Reviewable](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/161)

### CODE REVIEW

**Comment by mtlynch** [comment]
In the future, we should always plan to go from Community -> Pro. Rather than Pro -> Community. 

We're going to have to merge these changes from Community -> Pro again anyway and it might generate some tricky merge conflicts. If we go Community -> Pro, we have a clean commit history because the pro changes are based on the same base commit from the community version.

**Comment by rw4nn** [comment]
You're right. I'll try something to see if that helps the next merge on pro.

From a dev perspective, it was easier/cleaner to work on the pro repo for this because I can develop taking everything that is impacted in consideration. Instead if I start working on community repo I'm thinking I might miss something that would pop up after when merging and implementing the rest on the pro repo.

But yeah, I understand that's it's messy working on pro, backporting on community then re-merging on pro :thinking:

**Comment by rw4nn** [comment]
So yes I get it there will be a new merge with conflicts on pro, tried it myself to see how it's gonna be, good thing is the conflicts are easily resolved (just need to always take the pro changes).

Next time I'll work on community first then pro, even though again from a dev perspective it's better to work on the whole area than work on a subset while thinking about the whole area.

**Comment by rw4nn** [comment]
Sorry @jotaen4tinypilot I'm putting you a lot as a reviewer :sweat_smile: but as you reviewed the pro one it's better to be you again here.

**Review by jotaen4tinypilot — APPROVED** [review]
> Sorry @jotaen4tinypilot I'm putting you a lot as a reviewer 😅 but as you reviewed the pro one it's better to be you again here.

No worries about the review requests 😸

This looks all good to me, I’ve also tested on the device.

**Pull request merged**
