### PR TITLE
Upgrade to Ansible 2.10.7.

### PR DESCRIPTION
**Pull request by jdeanwallace**
Resolves https://github.com/tiny-pilot/ansible-role-tinypilot-pro/issues/119

This PR upgrades Ansible from `2.9.13` to `2.10.7`. We're doing this [because we have no more blockers for upgrading](https://github.com/tiny-pilot/ansible-role-tinypilot-pro/issues/119#issuecomment-1209605304) and because we want to define our role dependencies in a standalone requirements file (instead of in the galaxy meta file) which is [only available in version `>=2.10`](https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#using-meta-requirements-yml).

# Notes

1. I've moved `requirements.yml`  to `meta/requirements.yml`. This is to avoid maintaining two dependency lists.
1. I've switched our molecule test docker image from `mtlynch/debian10-ansible:2.9.13` to `geerlingguy/docker-debian10-ansible`. Geerlingguy only [maintains the latest ansible version](https://hub.docker.com/r/geerlingguy/docker-debian10-ansible/tags), but we anyway install a specific version of ansible during the test. We're already doing this with the [Debian 11 image](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/85a8eef4f4938af9e3047266c25c91d37b3d06c4/molecule/default/molecule.yml#L15).
1. Ansible `2.10.7` is not the latest patched version ([on github](https://github.com/ansible/ansible/tree/v2.10.17)), but it is the latest 2.10 release [on pypi](https://pypi.org/project/ansible/#history).
1. This PR has been marked as resolving [this issue](https://github.com/tiny-pilot/ansible-role-tinypilot-pro/issues/119), but that's only technically true once this code reaches the `master` branch (which might be a month or so). Are we okay with the `ansible-role-tinypilot-pro` build being broken on master until then? Again, I think the failed build is just a molecule testing issue and won't impact clients. If not, we can revert the change and re-apply it to the `update-overhaul` branch instead.
1. I explained [here](https://github.com/tiny-pilot/tinypilot/pull/1086#issue-1335982536) why we need to specify a user when running `ansible-playbook`. However, this is not strictly needed for our [`update-video-settings` script](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/85a8eef4f4938af9e3047266c25c91d37b3d06c4/files/update-video-settings#L75) because we skip any tasks that uses the undefined `ansible_user` variable. But for the sake of consistency, I have also specified a user when running `ansible-playbook`.

<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/ansible-role-tinypilot/213">Review on CodeApprove</a>

### CODE REVIEW

**Comment by jdeanwallace** [comment]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ansible-role-tinypilot/213)

⏳ @mtlynch please review this Pull Request

**Review by mtlynch — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ansible-role-tinypilot/213)


Approved on CodeApprove
✔️ Approved (2 unresolved comments)

LGTM!

<hr />

In: **files/update-video-settings**:

```
> Line 75
  --user "${USER}" \
```
I'd rather just set it in `ansible.cfg` (per your [other note](https://github.com/tiny-pilot/tinypilot/pull/1086#issue-1335982536)) because that's easier than remembering this flag every time. And it makes it obvious we always run Ansible as root.

<hr />

In: **molecule/requirements.txt**:

```
> Line 11
ansible==2.10.7
```
When we update direct dependencies, we also need to update indirect dependencies. I created a PR that fixes this:

https://github.com/tiny-pilot/ansible-role-tinypilot/pull/215


<hr />

👀 @jdeanwallace it's your turn please take a look

**Review by jdeanwallace — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ansible-role-tinypilot/213)



<hr />

In: **files/update-video-settings**:
Done.

<hr />

In: **molecule/requirements.txt**:

```
> Line 11
ansible==2.10.7
```
Thanks, merged.

**Review by mtlynch — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ansible-role-tinypilot/213)

Approved: I have approved this change on CodeApprove and all of my comments have been resolved.

**Pull request merged**
