### PR TITLE
Write overview and introduction to `configfs`

### PR DESCRIPTION
**Pull request by jotaen4tinypilot**
When working on https://github.com/tiny-pilot/ansible-role-tinypilot-pro/pull/86, it took me a while again to wrap my head around the quirks and inner workings of `configfs`. I remember from a year ago, when working on mass storage initially, I also struggled to understand it in the beginning. Unfortunately, there is not too much introductory documentation available online.

Therefore, I thought it would be worthwhile to write up our own overview, to remind our future selves (and potentially new developers too) and get up to speed a bit quicker.

When it comes to the behaviour of configfs, I think we shouldn’t repeat the same general comments all over the place, e.g. why we use `rmdir` instead of `rm -rf` for non-empty configfs directories. This is just how configfs works in general, not something that’s specific about our particular use case. While it’s easy to forget about these details, we could create a lot of unwanted noise that way. So maybe it’s sufficient to maintain one central primer instead.

Thoughts? @mtlynch @jdeanwallace @rw4nn 

Not sure `docs/...` is the right place?

---
This change is [Reviewable](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/185)

### CODE REVIEW

**Review by mtlynch — CHANGES_REQUESTED** [review]
This looks good to me from a high level, but I'll defer to others for a more thorough review. I support documenting it, and I think this is a good location.

> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/185#-:-MxBpIdJ0ufczx0tXSZ1:b-ndtbiz)* status: 0 of 1 LGTMs obtained

___
*[docs/usb-gadget-driver.md, line 1 at r1](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/185#-MxBpBmD-mFFbWXXhDMg:-MxBpBmD-mFFbWXXhDMh:b-1cwfdw) ([raw file](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/88d643d9e6789c973e2d2a604bb1c4bf515959f7/docs/usb-gadget-driver.md#L1)):*
> ```Markdown
> # USB Gadget Driver and `configfs`
> ```

Can we link back to this document from `init-usb-gadget` and any other files that touch configfs?
___
*[docs/usb-gadget-driver.md, line 3 at r1](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/185#-MxBoNrn6vqmBqm0Mmxk:-MxBoNrn6vqmBqm0Mmxl:b-y6rkmo) ([raw file](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/88d643d9e6789c973e2d2a604bb1c4bf515959f7/docs/usb-gadget-driver.md#L3)):*
> ```Markdown
> # USB Gadget Driver and `configfs`
> 
> We use `configfs` for configuring the USB gadget driver. Since `configfs` can
> ```

Can we get rid of the line breaks at 80 chars? Our general Markdown style is to not break lines except to break up paragraphs.

**Review by jdeanwallace — APPROVED** [review]
Despite me working on usb gadget before, I learned a few new things from reading this overview. A much needed read, thanks! :lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/185#-:-MxEP-aj4PZUrf4mZi41:b-eh6s1s)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Review by jotaen4tinypilot — COMMENTED** [review]
I’ll leave this PR open until @jdeanwallace gets around to the review of https://github.com/tiny-pilot/ansible-role-tinypilot-pro/pull/86. That way, we can ultimately check whether this write-up is sufficient, or whether we need to add or clarify things before merging.

> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/185#-:-MxFkAm8-JMMXwWDuo1D:b-ipyyqf)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[docs/usb-gadget-driver.md, line 1 at r1](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/185#-MxBpBmD-mFFbWXXhDMg:-MxFkCjk7w7-wXCyjUBw:b-hn3045) ([raw file](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/88d643d9e6789c973e2d2a604bb1c4bf515959f7/docs/usb-gadget-driver.md#L1)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

Can we link back to this document from `init-usb-gadget` and any other files that touch configfs?
</blockquote></details>

Since we don’t use Markdown in the docstrings, I thought it looked strange to put absolute paths for referencing the documentation file.

Therefore I just put `docs/usb-gadget-driver.md` consistently everywhere, in the hope that it’s clear enough how to find the file.
___
*[docs/usb-gadget-driver.md, line 3 at r1](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/185#-MxBoNrn6vqmBqm0Mmxk:-MxFkCU460aqFerYbm7j:b-896fix) ([raw file](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/88d643d9e6789c973e2d2a604bb1c4bf515959f7/docs/usb-gadget-driver.md#L3)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

Can we get rid of the line breaks at 80 chars? Our general Markdown style is to not break lines except to break up paragraphs.
</blockquote></details>

Done.

**Review by jdeanwallace — COMMENTED** [review]
Looks good.

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/185#-:-MxhcAUf9G95E_pzVEvm:b-vs1pr4)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[docs/usb-gadget-driver.md, line 15 at r2](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/185#-Mxh_bzm9386fkDmUMEg:-Mxh_bzm9386fkDmUMEh:b-5ijg72) ([raw file](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/154d1db2cbd5921eec8acc311360932ef2860a78/docs/usb-gadget-driver.md#L15)):*
> ```Markdown
> `configfs` is a virtual file system provided by the Linux kernel. It is mounted underneath `/sys/kernel/config/`. The file system does not map to a persistent disk, though, but the entire structure is held in memory.
> 
> The basic idea behind `configfs` is to interact with kernel functionality via file system APIs. So the file and directory entries in `configfs` are like a facade that’s directly wrapped around regular operating system APIs. Making changes to`configfs` files or folders is equivalent to making function calls (to system APIs), rather than merely persisting values on disk.
> ```

Add space



_Code quote:_
```Markdown
to`configfs`
```
___
*[docs/usb-gadget-driver.md, line 48 at r2](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/185#-Mxhamb38PR5JYpustPf:-Mxhamb38PR5JYpustPg:bz5hpep) ([raw file](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/154d1db2cbd5921eec8acc311360932ef2860a78/docs/usb-gadget-driver.md#L48)):*
(nit) Instead of making the parentheses it's own sentence, can we include the parentheses in the previous sentence?

For example:
> ... in a certain format (i.e., the parameters are essentially validated at write-time).

**Review by jotaen4tinypilot — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/185)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[docs/usb-gadget-driver.md, line 15 at r2](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/185#-Mxh_bzm9386fkDmUMEg:-Mxhqhet1PQamxT643VN:b-896fix) ([raw file](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/154d1db2cbd5921eec8acc311360932ef2860a78/docs/usb-gadget-driver.md#L15)):*
<details><summary><i>Previously, jdeanwallace (Jason Wallace) wrote…</i></summary><blockquote>

Add space
</blockquote></details>

Done.
___
*[docs/usb-gadget-driver.md, line 48 at r2](https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/185#-Mxhamb38PR5JYpustPf:-Mxhqhxe0zzwSP6d8RpN:b-896fix) ([raw file](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/154d1db2cbd5921eec8acc311360932ef2860a78/docs/usb-gadget-driver.md#L48)):*
<details><summary><i>Previously, jdeanwallace (Jason Wallace) wrote…</i></summary><blockquote>

(nit) Instead of making the parentheses it's own sentence, can we include the parentheses in the previous sentence?

For example:
> ... in a certain format (i.e., the parameters are essentially validated at write-time).
</blockquote></details>

Done.

**Pull request merged**
